{% set name = "pytfa" %}
{% set version = "0.9.4" %}
{% set build_number = '0' %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/EPFL-LCSB/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 66a7320c61042fabd43575b4179d9629304ca3d9f748681e94c8355b18cb4380

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.8

  run:
    - python >=3.8
    - equilibrator-api
    - equilibrator-cache
    - networkx
    - pandas
    - cobra <=0.24.0
    - bokeh >=0.12.1
    - numpy
    - optlang
    - scipy
    - tqdm
    - python-libsbml

test:
  imports:
    - pytfa
  commands:
    - pip check
  requires:
    - pip
    - pytest


about:
  home: https://github.com/EPFL-LCSB/pytfa
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: "pyTFA, Thermodynamics-based Flux Analysis in Python"
  doc_url: https://pytfa.readthedocs.io
  dev_url: https://github.com/EPFL-LCSB/pytfa

extra:
  recipe-maintainers:
    - weilandtd
