{% set name = "pytfa" %}
{% set version = "0.9.4" %}
{% set build_number = '0' %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/EPFL-LCSB/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 4300da87cde6d915db3bfddc288fcfb32885eedf00521651ac61f71b1aeee7e3

build:
  number: 2
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: true  # [py<38]

requirements:
  host:
    - pip
    - python

  run:
    - python
    - equilibrator-api
    - equilibrator-cache
    - networkx
    - pandas
    - cobra <=0.24.0
    - bokeh >=0.12.1
    - depinfo <=1.6.0
    - numpy
    - optlang
    - scipy
    - tqdm
    - python-libsbml

test:
  imports:
    - pytfa
  commands:
    - pip check
  requires:
    - pip
    - pytest


about:
  home: https://github.com/EPFL-LCSB/pytfa
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: "pyTFA, Thermodynamics-based Flux Analysis in Python"
  doc_url: https://pytfa.readthedocs.io
  dev_url: https://github.com/EPFL-LCSB/pytfa

extra:
  recipe-maintainers:
    - weilandtd
